
project_id = "vgbpfraisdnzilymqbky"

[functions]
verify_jwt = false

[functions.restaurants]
verify_jwt = false

[functions.google-places]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false
