// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgbpfraisdnzilymqbky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnYnBmcmFpc2RuemlseW1xYmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDg1OTIsImV4cCI6MjA2MTM4NDU5Mn0.a-jJE6q7yrc4r9GtX6IKr2cNp2IC8EcOG1D2NrB8YGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);